### ISSUE TITLE
The order between optimizer and Sparsifier

### ISSUE THREAD

**Issue by Equationliu** [facebookresearch/spartan#1]
When the `optimizer` is initiated before `Sparsifier`, I found the grads of params in the optimizer are always `None`.
> I guess the `convert` process in `Sparsifier` somehow changed something.

Initiating the `optimizer` after the `Sparsifier` solves the issue for me, i.e.,
```
sparsifier_cfg = SparsifierConfig(sparsity_mode="spartan")
sparsifier = Sparsifier(model, sparsifier_cfg, total_iters=len(train_loader))
optimizer = ...
```
is this the normal case?

**Comment by kaishengtai** [comment]
Thanks for pointing out this issue!

Yes, since the Sparsifier modifies the model inplace by replacing `nn.Module` instances with `MaskedModule` instances, the optimizer should be created after the Sparsifier so that the correct parameters are captured.

I've corrected the example in the README to reflect this in [ca38b4c](https://github.com/facebookresearch/spartan/commit/ca38b4c53fa6720a514375a8c29065466c091419).
